#[registries.gitea]
#index="http://192.168.1.69:3000/GCGames/_cargo-index.git"

[net]
git-fetch-with-cli=true

[build]
rustc-wrapper=".cargo/bin/sccache"

[profile.dev]
opt-level = 1
lto = false
codegen-units = 12

[profile.dev.package."*"]
opt-level = 3
codegen-units = 1

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
linker="clang"
rustflags=["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
